# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194jPeVLNX541ix6GCbV9_RcJuKziws90
"""

pip install praw

REDDIT_CLIENT_ID = "K89KAmySFDLe7h9zCnL7Cg"
REDDIT_SECRET = "eunIg6MT78xb0_JfPKpRwapQLk6VQg"
REDDIT_USER_AGENT = "script:reddit-user-persona:v1.0 (by u/Harshitha)"

import praw

import logging
logging.getLogger("praw").setLevel(logging.ERROR)


# Initialize Reddit instance
reddit = praw.Reddit(
    client_id=REDDIT_CLIENT_ID,
    client_secret=REDDIT_SECRET,
    user_agent=REDDIT_USER_AGENT
)

def get_user_content(username):
    redditor = reddit.redditor(username)
    posts = [post for post in redditor.submissions.new(limit=10)]
    comments = [comment for comment in redditor.comments.new(limit=10)]
    return posts, comments

# Example usage:
username = "kojied"
posts, comments = get_user_content(username)

# Print a few to check
print("[Posts]")
for post in posts[:3]:
    print(f"Title: {post.title}\nText: {post.selftext}\nLink: https://reddit.com{post.permalink}\n")

print("\n[Comments]")
for comment in comments[:3]:
    print(f"Comment: {comment.body}\nLink: https://reddit.com{comment.permalink}\n")